# _config.yml

title:       Organic Ellie
description: "Clean, conscious living for modern mamas."
baseurl:     "" 
url:         "https://organicellie.com"

markdown:    kramdown
plugins:
  - jekyll-feed
